import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/sections/navbar/default";
import { Footer } from "@/components/ui/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <Navbar/>
        {children}
        <Footer/>
    </>
  );
}
